# Azure Pipeline for Databricks CI/CD
#
# Build and releases the Databricks data and ML code. 
# 
# Build:
# * Runs unit and integration tests for handling requests
# * Build a virtual environment and archive for deployment.
# Releases:
# * Deploys ...
# 


trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - data_ops/*
    - cicd/databricks/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - data_ops/*
    - cicd/databricks/*

stages:
- stage: Build
  variables:
  - name: buildArtifactPath
    value:  'cicd/databricks'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: databricks.build.yml
