# Azure Pipeline for Databricks CI/CD
#
# Build and releases the Databricks data and ML code. 
# 
# Build:
# * Runs unit and integration tests for handling requests
# * Build a virtual environment and archive for deployment.
# Releases:
# * Deploys ...
# 


trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - data_ops/*
    - cicd/databricks/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - data_ops/*
    - cicd/databricks/*

variables:
- name: productionReady
  value: true
- name: buildArtifactPath
  value:  'cicd/databricks'
- name: pipelineArtifactName
  value:  'databricks-dev-build'
- group: mlops-dev

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: databricks.build.yml

- stage: ReleaseDEV
  displayName: DEV Release
  variables:
  - name: dockerRegistry
    value:  'mlops-acr'
  condition: eq('${{ variables.productionReady }}', true)
  jobs:
  - template: databricks.release.yml
    parameters:
      environment: dev

- stage: ReleaseINT
  displayName: INT Release
  condition: eq('${{ variables.productionReady }}', true)
  jobs:
  - template: databricks.release.yml
    parameters:
      environment: int
 
- stage: ReleasePRD
  displayName: PRD Release
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'), eq('${{ variables.productionReady }}', true))
  jobs:
  - template: databricks.release.yml
    parameters:
      environment: prd