# Azure Pipeline for Databricks CI/CD
#
# Build and releases the Databricks data and ML code. 
# 
# Build:
# * Runs unit and integration tests for handling requests
# * Build a virtual environment and archive for deployment.
# Releases:
# * Deploys ...
# 


trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - data_ops/*
    - cicd/databricks/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - data_ops/*
    - cicd/databricks/*

variables:
- name: productionReady
  value: false
- group: mlops-dev

stages:
- stage: Build
  variables:
  - name: buildArtifactPath
    value:  'cicd/databricks'
  - name: pipelineArtifactName
    value:  'databricks-dev-build'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: databricks.build.yml

- stage: ReleaseDEV
  displayName: DEV Release
  variables:
  - name: dockerRegistry
    value:  'mlops-acr'
  condition: eq('${{ variables.productionReady }}', false)
  jobs:
  - template: databricks.release.yml
    parameters:
      environment: dev